"""Prepare extracted prose for faithful, listenable audiobook narration."""

from .artifacts import (
    ArtifactValidationError,
    atomic_save_prepared_book,
    load_prepared_book,
    refresh_hashes,
    render_prepared_markdown,
    save_prepared_book,
    save_prepared_markdown,
    sha256_file,
    sha256_text,
    source_metadata_for_path,
    validate_artifact,
)
from .normalization import (
    is_markdown_heading,
    is_scene_marker,
    normalize_paragraph,
    normalize_text,
)
from .pipeline import (
    CheckpointCallback,
    NarrationPreparationPipeline,
    PreparationPipeline,
    prepare_book,
)
from .prompting import RESPONSE_JSON_SCHEMA, SYSTEM_PROMPT, build_messages
from .providers import (
    DEFAULT_OLLAMA_BASE_URL,
    DEFAULT_OLLAMA_MODEL,
    NarrationPreparationProvider,
    OllamaProvider,
    ProviderFactory,
    ProviderError,
    ProviderResponseError,
    ProviderUnavailableError,
    available_providers,
    create_provider,
    register_provider,
)
from .segmentation import (
    DEFAULT_CONTEXT_CHARS,
    DEFAULT_MAX_UNIT_CHARS,
    DEFAULT_TARGET_UNIT_CHARS,
    SourceUnit,
    segment_text,
)
from .types import (
    DEFAULT_POLICY,
    DEFAULT_PROMPT_VERSION,
    SCHEMA_VERSION,
    PreparedBook,
    PreparedChapter,
    PreparedUnit,
    PreparationEdit,
    PreparationRequest,
    PreparationResult,
    ProviderMetadata,
    SourceMetadata,
    UnitKind,
)
from .validation import (
    PreparationValidationError,
    ValidationPolicy,
    ValidationReport,
    mask_citations,
    validate_preparation,
)

__all__ = [
    "ArtifactValidationError",
    "CheckpointCallback",
    "DEFAULT_CONTEXT_CHARS",
    "DEFAULT_MAX_UNIT_CHARS",
    "DEFAULT_OLLAMA_BASE_URL",
    "DEFAULT_OLLAMA_MODEL",
    "DEFAULT_POLICY",
    "DEFAULT_PROMPT_VERSION",
    "DEFAULT_TARGET_UNIT_CHARS",
    "NarrationPreparationPipeline",
    "NarrationPreparationProvider",
    "OllamaProvider",
    "ProviderFactory",
    "PreparationEdit",
    "PreparationPipeline",
    "PreparationRequest",
    "PreparationResult",
    "PreparationValidationError",
    "PreparedBook",
    "PreparedChapter",
    "PreparedUnit",
    "ProviderError",
    "ProviderMetadata",
    "ProviderResponseError",
    "ProviderUnavailableError",
    "RESPONSE_JSON_SCHEMA",
    "SCHEMA_VERSION",
    "SYSTEM_PROMPT",
    "SourceMetadata",
    "SourceUnit",
    "UnitKind",
    "ValidationPolicy",
    "ValidationReport",
    "atomic_save_prepared_book",
    "available_providers",
    "build_messages",
    "create_provider",
    "is_markdown_heading",
    "is_scene_marker",
    "load_prepared_book",
    "mask_citations",
    "normalize_paragraph",
    "normalize_text",
    "prepare_book",
    "refresh_hashes",
    "register_provider",
    "render_prepared_markdown",
    "save_prepared_book",
    "save_prepared_markdown",
    "segment_text",
    "sha256_file",
    "sha256_text",
    "source_metadata_for_path",
    "validate_artifact",
    "validate_preparation",
]
